export interface Factura {
  CLI_CODIGO: number;
  CLI_DIRECCION: string;
  CLI_EMAIL: string;
  CLI_IDENTIFICACION: string;
  CLI_NOMBRE: string;
  CLI_TELEFONO: string;
  CLI_TIPOIDE: string;
  EMP_CODIGO: number;
  ITE_CODIGO: number;
  ITE_COSTO: number;
  ITE_EXISTENCIA: number;
  ITE_DETALLES: [];
  LOC_CODIGO: number;
  PTO_CODIGO: number;
  USU_CODIGO: number;
  VDR_CODIGO: number;
  VED_CODIGO: number;
  VEN_CAMPO1: string;
  VEN_CAMPO2: string;
  VEN_CAMPO3: string;
  VEN_CLAVEACCESO: string;
  VEN_CODIGO: string;
  VEN_COMISION: number;
  VEN_DESCUENTO: number;
  VEN_ESTABLECIMIENTO: number;
  VEN_ESTADO: number;
  VEN_FAUTORIZA: number;
  VEN_FECHA: string;
  VEN_FPAGO: string;
  VEN_GUIA: string;
  VEN_ICE: number;
  VEN_IMPRESO: number;
  VEN_IVA: number;
  VEN_NUMERO: number;
  VEN_PTOEMISION: number;
  VEN_RETENCION: number;
  VEN_SRI: number;
  VEN_SUBTOTAL: number;
  VEN_SUBTOTAL0: number;
  VEN_SUBTOTAL12: number;
  VEN_SUBTOTALEXCENTIVA: number;
  VEN_SUBTOTALNOIVA: number;
  VEN_TIPODOC: string;
  VEN_TOTAL: number;
  VEN_UKEY: string;
  VEN_VALOR1: string;
  VEN_VALOR2: string;
  VEN_VALOR3: string;
}

export interface FacturaDetalle {
  ITE_BARRAS: string;
  ITE_CODIGO: string;
  ITE_DESCRIPCION: string;
  ITE_CANTIDAD: number;
  VED_DET_CANTIDAD: number;
  VED_CANTIDAD: number;
  VED_DESCUENTO: number;
  VED_IMPUESTO: number;
  VED_PORCENTAJE: number;
  VED_PUNITARIO: number;
  VED_PUNITARIOIVA: number;
  VED_VALOR: number;
  VEN_CODIGO: string;
  VED_UKEY: string;
  KDX_CODIGO: string,
}

export const initFactura = (): Factura => ({
  CLI_CODIGO: 0,
  CLI_DIRECCION: "S/N",
  CLI_EMAIL: "-",
  CLI_IDENTIFICACION: "9999999999999",
  CLI_NOMBRE: "CONSUMIDOR FINAL",
  CLI_TELEFONO: "-",
  CLI_TIPOIDE: "-",
  EMP_CODIGO: 0,
  ITE_CODIGO: 0,
  ITE_COSTO: 0,
  ITE_EXISTENCIA: 0,
  ITE_DETALLES: [],
  LOC_CODIGO: 0,
  PTO_CODIGO: 0,
  USU_CODIGO: 0,
  VDR_CODIGO: 0,
  VED_CODIGO: 0,
  VEN_CAMPO1: "",
  VEN_CAMPO2: "",
  VEN_CAMPO3: "",
  VEN_CLAVEACCESO: "",
  VEN_CODIGO: "",
  VEN_COMISION: 0,
  VEN_DESCUENTO: 0,
  VEN_ESTABLECIMIENTO: 1,
  VEN_ESTADO: 1,
  VEN_FAUTORIZA: 1,
  VEN_FECHA: new Date().toISOString().split("T")[0],
  VEN_FPAGO: "01",
  VEN_GUIA: "-",
  VEN_ICE: 0.0,
  VEN_IMPRESO: 0.0,
  VEN_IVA: 0.0,
  VEN_NUMERO: 1,
  VEN_PTOEMISION: 1,
  VEN_RETENCION: 0.0,
  VEN_SRI: 0.0,
  VEN_SUBTOTAL: 0.0,
  VEN_SUBTOTAL0: 0.0,
  VEN_SUBTOTAL12: 0.0,
  VEN_SUBTOTALEXCENTIVA: 0.0,
  VEN_SUBTOTALNOIVA: 0.0,
  VEN_TIPODOC: "",
  VEN_TOTAL: 0.0,
  VEN_UKEY: "",
  VEN_VALOR1: "",
  VEN_VALOR2: "",
  VEN_VALOR3: "",
});
