export interface Factura {
  CLI_CODIGO: number;
  CLI_DIRECCION: string;
  CLI_EMAIL: string;
  CLI_IDENTIFICACION: string;
  CLI_NOMBRE: string;
  CLI_TELEFONO: string;
  CLI_TIPOIDE: string;
  EMP_CODIGO: number;
  ITE_CODIGO: number;
  ITE_COSTO: number;
  ITE_EXISTENCIA: number;
  ITE_DETALLES: [];
  LOC_CODIGO: number;
  PTO_CODIGO: number;
  USU_CODIGO: number;
  VDR_CODIGO: number;
  VED_CODIGO: number;
  VEN_CAMPO1: string;
  VEN_CAMPO2: string;
  VEN_CAMPO3: string;
  VEN_CLAVEACCESO: string;
  VEN_CODIGO: string;
  VEN_COMISION: number;
  VEN_DESCUENTO: number;
  VEN_ESTABLECIMIENTO: string;
  VEN_ESTADO: number;
  VEN_FAUTORIZA: string;
  VEN_FECHA: string;
  VEN_FPAGO: number;
  VEN_GUIA: string;
  VEN_ICE: number;
  VEN_IMPRESO: number;
  VEN_IVA: number;
  VEN_NUMERO: string;
  VEN_PTOEMISION: string;
  VEN_RETENCION: number;
  VEN_SRI: number;
  VEN_SUBTOTAL: number;
  VEN_SUBTOTAL0: number;
  VEN_SUBTOTAL12: number;
  VEN_SUBTOTALEXCENTIVA: number;
  VEN_SUBTOTALNOIVA: number;
  VEN_TIPODOC: string;
  VEN_TOTAL: number;
  VEN_UKEY: string;
  VEN_VALOR1: string;
  VEN_VALOR2: string;
  VEN_VALOR3: string;
}

export interface FacturaDetalle {
  ITE_BARRAS: string;
  ITE_CODIGO: string;
  ITE_DESCRIPCION: string;
  ITE_CANTIDAD: number;
  VED_CANTIDAD: number;
  VED_DESCUENTO: number;
  VED_IMPUESTO: number;
  VED_PORCENTAJE: number;
  VED_PUNITARIO: number;
  VED_PUNITARIOIVA: number;
  VED_VALOR: number;
  VEN_CODIGO: string;
  VED_UKEY: string;
}

export const initFactura: Factura = {
  CLI_CODIGO: 0,
  CLI_DIRECCION: "",
  CLI_EMAIL: "",
  CLI_IDENTIFICACION: "",
  CLI_NOMBRE: "",
  CLI_TELEFONO: "",
  CLI_TIPOIDE: "",
  EMP_CODIGO: 0,
  ITE_CODIGO: 0,
  ITE_COSTO: 0,
  ITE_EXISTENCIA: 0,
  ITE_DETALLES: [],
  LOC_CODIGO: 0,
  PTO_CODIGO: 0,
  USU_CODIGO: 0,
  VDR_CODIGO: 0,
  VED_CODIGO: 0,
  VEN_CAMPO1: "",
  VEN_CAMPO2: "",
  VEN_CAMPO3: "",
  VEN_CLAVEACCESO: "",
  VEN_CODIGO: "",
  VEN_COMISION: 0,
  VEN_DESCUENTO: 0,
  VEN_ESTABLECIMIENTO: "",
  VEN_ESTADO: 0,
  VEN_FAUTORIZA: "",
  VEN_FECHA: "",
  VEN_FPAGO: 0,
  VEN_GUIA: "",
  VEN_ICE: 0,
  VEN_IMPRESO: 0,
  VEN_IVA: 0,
  VEN_NUMERO: "",
  VEN_PTOEMISION: "",
  VEN_RETENCION: 0,
  VEN_SRI: 0,
  VEN_SUBTOTAL: 0,
  VEN_SUBTOTAL0: 0,
  VEN_SUBTOTAL12: 0,
  VEN_SUBTOTALEXCENTIVA: 0,
  VEN_SUBTOTALNOIVA: 0,
  VEN_TIPODOC: "",
  VEN_TOTAL: 0,
  VEN_UKEY: "",
  VEN_VALOR1: "",
  VEN_VALOR2: "",
  VEN_VALOR3: "",
};
